//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:40:40 PM EDT 
//


package com.isis.util.xero;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timezoneCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="timezoneCode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="DATELINESTANDARDTIME"/>
 *     &lt;enumeration value="UTC11"/>
 *     &lt;enumeration value="HAWAIIANSTANDARDTIME"/>
 *     &lt;enumeration value="ALASKANSTANDARDTIME"/>
 *     &lt;enumeration value="PACIFICSTANDARDTIME(MEXICO)"/>
 *     &lt;enumeration value="PACIFICSTANDARDTIME"/>
 *     &lt;enumeration value="MOUNTAINSTANDARDTIME"/>
 *     &lt;enumeration value="MOUNTAINSTANDARDTIME(MEXICO)"/>
 *     &lt;enumeration value="USMOUNTAINSTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALAMERICASTANDARDTIME"/>
 *     &lt;enumeration value="CANADACENTRALSTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALSTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALSTANDARDTIME(MEXICO)"/>
 *     &lt;enumeration value="SAPACIFICSTANDARDTIME"/>
 *     &lt;enumeration value="USEASTERNSTANDARDTIME"/>
 *     &lt;enumeration value="EASTERNSTANDARDTIME"/>
 *     &lt;enumeration value="VENEZUELASTANDARDTIME"/>
 *     &lt;enumeration value="PARAGUAYSTANDARDTIME"/>
 *     &lt;enumeration value="PACIFICSASTANDARDTIME"/>
 *     &lt;enumeration value="SAWESTERNSTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALBRAZILIANSTANDARDTIME"/>
 *     &lt;enumeration value="ATLANTICSTANDARDTIME"/>
 *     &lt;enumeration value="NEWFOUNDLANDSTANDARDTIME"/>
 *     &lt;enumeration value="SAEASTERNSTANDARDTIME"/>
 *     &lt;enumeration value="MONTEVIDEOSTANDARDTIME"/>
 *     &lt;enumeration value="ARGENTINASTANDARDTIME"/>
 *     &lt;enumeration value="BAHIASTANDARDTIME"/>
 *     &lt;enumeration value="GREENLANDSTANDARDTIME"/>
 *     &lt;enumeration value="ESOUTHAMERICASTANDARDTIME"/>
 *     &lt;enumeration value="MIDATLANTICSTANDARDTIME"/>
 *     &lt;enumeration value="UTC02"/>
 *     &lt;enumeration value="CAPEVERDESTANDARDTIME"/>
 *     &lt;enumeration value="AZORESSTANDARDTIME"/>
 *     &lt;enumeration value="MOROCCOSTANDARDTIME"/>
 *     &lt;enumeration value="UTC"/>
 *     &lt;enumeration value="GREENWICHSTANDARDTIME"/>
 *     &lt;enumeration value="GMTSTANDARDTIME"/>
 *     &lt;enumeration value="ROMANCESTANDARDTIME"/>
 *     &lt;enumeration value="NAMIBIASTANDARDTIME"/>
 *     &lt;enumeration value="WCENTRALAFRICASTANDARDTIME"/>
 *     &lt;enumeration value="WEUROPESTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALEUROPESTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALEUROPEANSTANDARDTIME"/>
 *     &lt;enumeration value="MIDDLEEASTSTANDARDTIME"/>
 *     &lt;enumeration value="SYRIASTANDARDTIME"/>
 *     &lt;enumeration value="SOUTHAFRICASTANDARDTIME"/>
 *     &lt;enumeration value="TURKEYSTANDARDTIME"/>
 *     &lt;enumeration value="GTBSTANDARDTIME"/>
 *     &lt;enumeration value="ISRAELSTANDARDTIME"/>
 *     &lt;enumeration value="JORDANSTANDARDTIME"/>
 *     &lt;enumeration value="EEUROPESTANDARDTIME"/>
 *     &lt;enumeration value="FLESTANDARDTIME"/>
 *     &lt;enumeration value="EGYPTSTANDARDTIME"/>
 *     &lt;enumeration value="ARABICSTANDARDTIME"/>
 *     &lt;enumeration value="ARABSTANDARDTIME"/>
 *     &lt;enumeration value="KALININGRADSTANDARDTIME"/>
 *     &lt;enumeration value="EAFRICASTANDARDTIME"/>
 *     &lt;enumeration value="IRANSTANDARDTIME"/>
 *     &lt;enumeration value="RUSSIANSTANDARDTIME"/>
 *     &lt;enumeration value="MAURITIUSSTANDARDTIME"/>
 *     &lt;enumeration value="CAUCASUSSTANDARDTIME"/>
 *     &lt;enumeration value="ARABIANSTANDARDTIME"/>
 *     &lt;enumeration value="AZERBAIJANSTANDARDTIME"/>
 *     &lt;enumeration value="GEORGIANSTANDARDTIME"/>
 *     &lt;enumeration value="AFGHANISTANSTANDARDTIME"/>
 *     &lt;enumeration value="PAKISTANSTANDARDTIME"/>
 *     &lt;enumeration value="WESTASIASTANDARDTIME"/>
 *     &lt;enumeration value="SRILANKASTANDARDTIME"/>
 *     &lt;enumeration value="INDIASTANDARDTIME"/>
 *     &lt;enumeration value="NEPALSTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALASIASTANDARDTIME"/>
 *     &lt;enumeration value="BANGLADESHSTANDARDTIME"/>
 *     &lt;enumeration value="EKATERINBURGSTANDARDTIME"/>
 *     &lt;enumeration value="MYANMARSTANDARDTIME"/>
 *     &lt;enumeration value="NCENTRALASIASTANDARDTIME"/>
 *     &lt;enumeration value="SEASIASTANDARDTIME"/>
 *     &lt;enumeration value="NORTHASIASTANDARDTIME"/>
 *     &lt;enumeration value="WAUSTRALIASTANDARDTIME"/>
 *     &lt;enumeration value="TAIPEISTANDARDTIME"/>
 *     &lt;enumeration value="SINGAPORESTANDARDTIME"/>
 *     &lt;enumeration value="ULAANBAATARSTANDARDTIME"/>
 *     &lt;enumeration value="CHINASTANDARDTIME"/>
 *     &lt;enumeration value="NORTHASIAEASTSTANDARDTIME"/>
 *     &lt;enumeration value="TOKYOSTANDARDTIME"/>
 *     &lt;enumeration value="KOREASTANDARDTIME"/>
 *     &lt;enumeration value="CENAUSTRALIASTANDARDTIME"/>
 *     &lt;enumeration value="AUSCENTRALSTANDARDTIME"/>
 *     &lt;enumeration value="WESTPACIFICSTANDARDTIME"/>
 *     &lt;enumeration value="YAKUTSKSTANDARDTIME"/>
 *     &lt;enumeration value="TASMANIASTANDARDTIME"/>
 *     &lt;enumeration value="AUSEASTERNSTANDARDTIME"/>
 *     &lt;enumeration value="EAUSTRALIASTANDARDTIME"/>
 *     &lt;enumeration value="VLADIVOSTOKSTANDARDTIME"/>
 *     &lt;enumeration value="CENTRALPACIFICSTANDARDTIME"/>
 *     &lt;enumeration value="NEWZEALANDSTANDARDTIME"/>
 *     &lt;enumeration value="UTC+12"/>
 *     &lt;enumeration value="KAMCHATKASTANDARDTIME"/>
 *     &lt;enumeration value="MAGADANSTANDARDTIME"/>
 *     &lt;enumeration value="FIJISTANDARDTIME"/>
 *     &lt;enumeration value="SAMOASTANDARDTIME"/>
 *     &lt;enumeration value="TONGASTANDARDTIME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "timezoneCode")
@XmlEnum
public enum TimezoneCode {


    /**
     * (UTC-12:00) International Date Line West
     * 
     */
    DATELINESTANDARDTIME("DATELINESTANDARDTIME"),

    /**
     * (UTC-11:00) Coordinated Universal Time-11
     * 
     */
    @XmlEnumValue("UTC11")
    UTC_11("UTC11"),

    /**
     * (UTC-10:00) Hawaii
     * 
     */
    HAWAIIANSTANDARDTIME("HAWAIIANSTANDARDTIME"),

    /**
     * (UTC-09:00) Alaska
     * 
     */
    ALASKANSTANDARDTIME("ALASKANSTANDARDTIME"),

    /**
     * (UTC-08:00) Baja California
     * 
     */
    @XmlEnumValue("PACIFICSTANDARDTIME(MEXICO)")
    PACIFICSTANDARDTIME_MEXICO("PACIFICSTANDARDTIME(MEXICO)"),

    /**
     * (UTC-08:00) Pacific Time (US & Canada)
     * 
     */
    PACIFICSTANDARDTIME("PACIFICSTANDARDTIME"),

    /**
     * (UTC-07:00) Mountain Time (US & Canada)
     * 
     */
    MOUNTAINSTANDARDTIME("MOUNTAINSTANDARDTIME"),

    /**
     * (UTC-07:00) Chihuahua, La Paz, Mazatlan
     * 
     */
    @XmlEnumValue("MOUNTAINSTANDARDTIME(MEXICO)")
    MOUNTAINSTANDARDTIME_MEXICO("MOUNTAINSTANDARDTIME(MEXICO)"),

    /**
     * (UTC-07:00) Arizona
     * 
     */
    USMOUNTAINSTANDARDTIME("USMOUNTAINSTANDARDTIME"),

    /**
     * (UTC-06:00) Central America
     * 
     */
    CENTRALAMERICASTANDARDTIME("CENTRALAMERICASTANDARDTIME"),

    /**
     * (UTC-06:00) Saskatchewan
     * 
     */
    CANADACENTRALSTANDARDTIME("CANADACENTRALSTANDARDTIME"),

    /**
     * (UTC-06:00) Central Time (US & Canada)
     * 
     */
    CENTRALSTANDARDTIME("CENTRALSTANDARDTIME"),

    /**
     * (UTC-06:00) Guadalajara, Mexico City, Monterrey
     * 
     */
    @XmlEnumValue("CENTRALSTANDARDTIME(MEXICO)")
    CENTRALSTANDARDTIME_MEXICO("CENTRALSTANDARDTIME(MEXICO)"),

    /**
     * (UTC-05:00) Bogota, Lima, Quito
     * 
     */
    SAPACIFICSTANDARDTIME("SAPACIFICSTANDARDTIME"),

    /**
     * (UTC-05:00) Indiana (East)
     * 
     */
    USEASTERNSTANDARDTIME("USEASTERNSTANDARDTIME"),

    /**
     * (UTC-05:00) Eastern Time (US & Canada)
     * 
     */
    EASTERNSTANDARDTIME("EASTERNSTANDARDTIME"),

    /**
     * (UTC-04:30) Caracas
     * 
     */
    VENEZUELASTANDARDTIME("VENEZUELASTANDARDTIME"),

    /**
     * (UTC-04:00) Asuncion
     * 
     */
    PARAGUAYSTANDARDTIME("PARAGUAYSTANDARDTIME"),

    /**
     * (UTC-04:00) Santiago
     * 
     */
    PACIFICSASTANDARDTIME("PACIFICSASTANDARDTIME"),

    /**
     * (UTC-04:00) Georgetown, La Paz, Manaus, San Juan
     * 
     */
    SAWESTERNSTANDARDTIME("SAWESTERNSTANDARDTIME"),

    /**
     * (UTC-04:00) Cuiaba
     * 
     */
    CENTRALBRAZILIANSTANDARDTIME("CENTRALBRAZILIANSTANDARDTIME"),

    /**
     * (UTC-04:00) Atlantic Time (Canada)
     * 
     */
    ATLANTICSTANDARDTIME("ATLANTICSTANDARDTIME"),

    /**
     * (UTC-03:30) Newfoundland
     * 
     */
    NEWFOUNDLANDSTANDARDTIME("NEWFOUNDLANDSTANDARDTIME"),

    /**
     * (UTC-03:00) Cayenne, Fortaleza
     * 
     */
    SAEASTERNSTANDARDTIME("SAEASTERNSTANDARDTIME"),

    /**
     * (UTC-03:00) Montevideo
     * 
     */
    MONTEVIDEOSTANDARDTIME("MONTEVIDEOSTANDARDTIME"),

    /**
     * (UTC-03:00) Buenos Aires
     * 
     */
    ARGENTINASTANDARDTIME("ARGENTINASTANDARDTIME"),

    /**
     * (UTC-03:00) Salvador
     * 
     */
    BAHIASTANDARDTIME("BAHIASTANDARDTIME"),

    /**
     * (UTC-03:00) Greenland
     * 
     */
    GREENLANDSTANDARDTIME("GREENLANDSTANDARDTIME"),

    /**
     * (UTC-03:00) Brasilia
     * 
     */
    ESOUTHAMERICASTANDARDTIME("ESOUTHAMERICASTANDARDTIME"),

    /**
     * (UTC-02:00) Mid-Atlantic
     * 
     */
    MIDATLANTICSTANDARDTIME("MIDATLANTICSTANDARDTIME"),

    /**
     * (UTC-02:00) Coordinated Universal Time-02
     * 
     */
    @XmlEnumValue("UTC02")
    UTC_02("UTC02"),

    /**
     * (UTC-01:00) Cape Verde Is.
     * 
     */
    CAPEVERDESTANDARDTIME("CAPEVERDESTANDARDTIME"),

    /**
     * (UTC-01:00) Azores
     * 
     */
    AZORESSTANDARDTIME("AZORESSTANDARDTIME"),

    /**
     * (UTC) Casablanca
     * 
     */
    MOROCCOSTANDARDTIME("MOROCCOSTANDARDTIME"),

    /**
     * (UTC) Coordinated Universal Time
     * 
     */
    UTC("UTC"),

    /**
     * (UTC) Monrovia, Reykjavik
     * 
     */
    GREENWICHSTANDARDTIME("GREENWICHSTANDARDTIME"),

    /**
     * (UTC) Dublin, Edinburgh, Lisbon, London
     * 
     */
    GMTSTANDARDTIME("GMTSTANDARDTIME"),

    /**
     * (UTC+01:00) Brussels, Copenhagen, Madrid, Paris
     * 
     */
    ROMANCESTANDARDTIME("ROMANCESTANDARDTIME"),

    /**
     * (UTC+01:00) Windhoek
     * 
     */
    NAMIBIASTANDARDTIME("NAMIBIASTANDARDTIME"),

    /**
     * (UTC+01:00) West Central Africa
     * 
     */
    WCENTRALAFRICASTANDARDTIME("WCENTRALAFRICASTANDARDTIME"),

    /**
     * (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
     * 
     */
    WEUROPESTANDARDTIME("WEUROPESTANDARDTIME"),

    /**
     * (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
     * 
     */
    CENTRALEUROPESTANDARDTIME("CENTRALEUROPESTANDARDTIME"),

    /**
     * (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb
     * 
     */
    CENTRALEUROPEANSTANDARDTIME("CENTRALEUROPEANSTANDARDTIME"),

    /**
     * (UTC+02:00) Beirut
     * 
     */
    MIDDLEEASTSTANDARDTIME("MIDDLEEASTSTANDARDTIME"),

    /**
     * (UTC+02:00) Damascus
     * 
     */
    SYRIASTANDARDTIME("SYRIASTANDARDTIME"),

    /**
     * (UTC+02:00) Harare, Pretoria
     * 
     */
    SOUTHAFRICASTANDARDTIME("SOUTHAFRICASTANDARDTIME"),

    /**
     * (UTC+02:00) Istanbul
     * 
     */
    TURKEYSTANDARDTIME("TURKEYSTANDARDTIME"),

    /**
     * (UTC+02:00) Athens, Bucharest
     * 
     */
    GTBSTANDARDTIME("GTBSTANDARDTIME"),

    /**
     * (UTC+02:00) Jerusalem
     * 
     */
    ISRAELSTANDARDTIME("ISRAELSTANDARDTIME"),

    /**
     * (UTC+02:00) Amman
     * 
     */
    JORDANSTANDARDTIME("JORDANSTANDARDTIME"),

    /**
     * (UTC+02:00) Nicosia
     * 
     */
    EEUROPESTANDARDTIME("EEUROPESTANDARDTIME"),

    /**
     * (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
     * 
     */
    FLESTANDARDTIME("FLESTANDARDTIME"),

    /**
     * (UTC+02:00) Cairo
     * 
     */
    EGYPTSTANDARDTIME("EGYPTSTANDARDTIME"),

    /**
     * (UTC+03:00) Baghdad
     * 
     */
    ARABICSTANDARDTIME("ARABICSTANDARDTIME"),

    /**
     * (UTC+03:00) Kuwait, Riyadh
     * 
     */
    ARABSTANDARDTIME("ARABSTANDARDTIME"),

    /**
     * (UTC+03:00) Kaliningrad, Minsk
     * 
     */
    KALININGRADSTANDARDTIME("KALININGRADSTANDARDTIME"),

    /**
     * (UTC+03:00) Nairobi
     * 
     */
    EAFRICASTANDARDTIME("EAFRICASTANDARDTIME"),

    /**
     * (UTC+03:30) Tehran
     * 
     */
    IRANSTANDARDTIME("IRANSTANDARDTIME"),

    /**
     * (UTC+04:00) Moscow, St. Petersburg, Volgograd
     * 
     */
    RUSSIANSTANDARDTIME("RUSSIANSTANDARDTIME"),

    /**
     * (UTC+04:00) Port Louis
     * 
     */
    MAURITIUSSTANDARDTIME("MAURITIUSSTANDARDTIME"),

    /**
     * (UTC+04:00) Yerevan
     * 
     */
    CAUCASUSSTANDARDTIME("CAUCASUSSTANDARDTIME"),

    /**
     * (UTC+04:00) Abu Dhabi, Muscat
     * 
     */
    ARABIANSTANDARDTIME("ARABIANSTANDARDTIME"),

    /**
     * (UTC+04:00) Baku
     * 
     */
    AZERBAIJANSTANDARDTIME("AZERBAIJANSTANDARDTIME"),

    /**
     * (UTC+04:00) Tbilisi
     * 
     */
    GEORGIANSTANDARDTIME("GEORGIANSTANDARDTIME"),

    /**
     * (UTC+04:30) Kabul
     * 
     */
    AFGHANISTANSTANDARDTIME("AFGHANISTANSTANDARDTIME"),

    /**
     * (UTC+05:00) Islamabad, Karachi
     * 
     */
    PAKISTANSTANDARDTIME("PAKISTANSTANDARDTIME"),

    /**
     * (UTC+05:00) Tashkent
     * 
     */
    WESTASIASTANDARDTIME("WESTASIASTANDARDTIME"),

    /**
     * (UTC+05:30) Sri Jayawardenepura
     * 
     */
    SRILANKASTANDARDTIME("SRILANKASTANDARDTIME"),

    /**
     * (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
     * 
     */
    INDIASTANDARDTIME("INDIASTANDARDTIME"),

    /**
     * (UTC+05:45) Kathmandu
     * 
     */
    NEPALSTANDARDTIME("NEPALSTANDARDTIME"),

    /**
     * (UTC+06:00) Astana
     * 
     */
    CENTRALASIASTANDARDTIME("CENTRALASIASTANDARDTIME"),

    /**
     * (UTC+06:00) Dhaka
     * 
     */
    BANGLADESHSTANDARDTIME("BANGLADESHSTANDARDTIME"),

    /**
     * (UTC+06:00) Ekaterinburg
     * 
     */
    EKATERINBURGSTANDARDTIME("EKATERINBURGSTANDARDTIME"),

    /**
     * (UTC+06:30) Yangon (Rangoon)
     * 
     */
    MYANMARSTANDARDTIME("MYANMARSTANDARDTIME"),

    /**
     * (UTC+07:00) Novosibirsk
     * 
     */
    NCENTRALASIASTANDARDTIME("NCENTRALASIASTANDARDTIME"),

    /**
     * (UTC+07:00) Bangkok, Hanoi, Jakarta
     * 
     */
    SEASIASTANDARDTIME("SEASIASTANDARDTIME"),

    /**
     * (UTC+08:00) Krasnoyarsk
     * 
     */
    NORTHASIASTANDARDTIME("NORTHASIASTANDARDTIME"),

    /**
     * (UTC+08:00) Perth
     * 
     */
    WAUSTRALIASTANDARDTIME("WAUSTRALIASTANDARDTIME"),

    /**
     * (UTC+08:00) Taipei
     * 
     */
    TAIPEISTANDARDTIME("TAIPEISTANDARDTIME"),

    /**
     * (UTC+08:00) Kuala Lumpur, Singapore
     * 
     */
    SINGAPORESTANDARDTIME("SINGAPORESTANDARDTIME"),

    /**
     * (UTC+08:00) Ulaanbaatar
     * 
     */
    ULAANBAATARSTANDARDTIME("ULAANBAATARSTANDARDTIME"),

    /**
     * (UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi
     * 
     */
    CHINASTANDARDTIME("CHINASTANDARDTIME"),

    /**
     * (UTC+09:00) Irkutsk
     * 
     */
    NORTHASIAEASTSTANDARDTIME("NORTHASIAEASTSTANDARDTIME"),

    /**
     * (UTC+09:00) Osaka, Sapporo, Tokyo
     * 
     */
    TOKYOSTANDARDTIME("TOKYOSTANDARDTIME"),

    /**
     * (UTC+09:00) Seoul
     * 
     */
    KOREASTANDARDTIME("KOREASTANDARDTIME"),

    /**
     * (UTC+09:30) Adelaide
     * 
     */
    CENAUSTRALIASTANDARDTIME("CENAUSTRALIASTANDARDTIME"),

    /**
     * (UTC+09:30) Darwin
     * 
     */
    AUSCENTRALSTANDARDTIME("AUSCENTRALSTANDARDTIME"),

    /**
     * (UTC+10:00) Guam, Port Moresby
     * 
     */
    WESTPACIFICSTANDARDTIME("WESTPACIFICSTANDARDTIME"),

    /**
     * (UTC+10:00) Yakutsk
     * 
     */
    YAKUTSKSTANDARDTIME("YAKUTSKSTANDARDTIME"),

    /**
     * (UTC+10:00) Hobart
     * 
     */
    TASMANIASTANDARDTIME("TASMANIASTANDARDTIME"),

    /**
     * (UTC+10:00) Canberra, Melbourne, Sydney
     * 
     */
    AUSEASTERNSTANDARDTIME("AUSEASTERNSTANDARDTIME"),

    /**
     * (UTC+10:00) Brisbane
     * 
     */
    EAUSTRALIASTANDARDTIME("EAUSTRALIASTANDARDTIME"),

    /**
     * (UTC+11:00) Vladivostok
     * 
     */
    VLADIVOSTOKSTANDARDTIME("VLADIVOSTOKSTANDARDTIME"),

    /**
     * (UTC+11:00) Solomon Is., New Caledonia
     * 
     */
    CENTRALPACIFICSTANDARDTIME("CENTRALPACIFICSTANDARDTIME"),

    /**
     * (UTC+12:00) Auckland, Wellington
     * 
     */
    NEWZEALANDSTANDARDTIME("NEWZEALANDSTANDARDTIME"),

    /**
     * (UTC+12:00) Coordinated Universal Time+12
     * 
     */
    @XmlEnumValue("UTC+12")
    UTC_12("UTC+12"),

    /**
     * (UTC+12:00) Petropavlovsk-Kamchatsky - Old
     * 
     */
    KAMCHATKASTANDARDTIME("KAMCHATKASTANDARDTIME"),

    /**
     * (UTC+12:00) Magadan
     * 
     */
    MAGADANSTANDARDTIME("MAGADANSTANDARDTIME"),

    /**
     * (UTC+12:00) Fiji
     * 
     */
    FIJISTANDARDTIME("FIJISTANDARDTIME"),

    /**
     * (UTC+13:00) Samoa
     * 
     */
    SAMOASTANDARDTIME("SAMOASTANDARDTIME"),

    /**
     * (UTC+13:00) Nuku'alofa
     * 
     */
    TONGASTANDARDTIME("TONGASTANDARDTIME");
    private final String value;

    TimezoneCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimezoneCode fromValue(String v) {
        for (TimezoneCode c: TimezoneCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
