//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:40:40 PM EDT 
//


package com.aireus.util.xero;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApiExceptionExtended complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApiExceptionExtended">
 *   &lt;complexContent>
 *     &lt;extension base="{}ApiException">
 *       &lt;sequence>
 *         &lt;element name="Elements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;element name="DataContractBase" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApiExceptionExtended", propOrder = {
    "elements"
})
public class ApiExceptionExtended
    extends ApiException
{

    @XmlElement(name = "Elements", required = true)
    protected ApiExceptionExtended.Elements elements;

    /**
     * Gets the value of the elements property.
     * 
     * @return
     *     possible object is
     *     {@link ApiExceptionExtended.Elements }
     *     
     */
    public ApiExceptionExtended.Elements getElements() {
        return elements;
    }

    /**
     * Sets the value of the elements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApiExceptionExtended.Elements }
     *     
     */
    public void setElements(ApiExceptionExtended.Elements value) {
        this.elements = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;element name="DataContractBase" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataContractBase"
    })
    public static class Elements {

        @XmlElement(name = "DataContractBase", required = true)
        protected Object dataContractBase;

        /**
         * Gets the value of the dataContractBase property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDataContractBase() {
            return dataContractBase;
        }

        /**
         * Sets the value of the dataContractBase property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDataContractBase(Object value) {
            this.dataContractBase = value;
        }

    }

}
